### ISSUE TITLE
Signature does not match error

### ISSUE THREAD

**Issue by jstewart99** [frudens/aws-api-sig-v4-filemaker#1]
Attempting to use this for Amazon STS (Secure Token Service) AssumeRole action.  I get an error that the signature does not match the one they generated.  Here's the parameters I'm using in the Task 0 tab (leaving out my Access Key and Secret key ID, but have confirmed those are correct):

URL: https://sts.amazonaws.com/?Action=AssumeRole&RoleArn=arn:aws:iam::[xxx]:role/amazon-seller-partner-role&RoleSessionName=test&Version=2011-06-15

Region: us-east-1
Service: sts
Method: Get
Body: (empty)

Test Request button returns:
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
  </Error>
  <RequestId>967c1575-2449-49c4-9234-fb05cfc9e9f7</RequestId>
</ErrorResponse>

I've been wrestling with this function on my own before I came across your solution here, which I was hoping would help, but am getting the same error.  Thanks in advance for any suggestions.

**Comment by teruhirokomaki** [comment]
Thank you for using it and for creating an issue!
I have checked the details of your error.

I will make the same request at hand and see if it reproduces.
I will comment if there is progress in my work.

**Comment by teruhirokomaki** [comment]
@jstewart99 
When I checked the request information using Node.js's aws-sdk, it looked like a screenshot.

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/31458364/216877358-2d70e8d4-4d35-409b-8fd1-5ce68bcbf3f9.png">

After doing the same, I was able to access it.

I will comment once.
I'll share it when the work settles down.

**Comment by jstewart99** [comment]
Thank you so much for this.  I was able to get it working with the information above (I was using GET instead of POST and had the Body in the URL rather than the CURL data).  I've spent hours/days trying to get this to work, so I REALLY appreciate your help!

**Comment by teruhirokomaki** [comment]
I'm glad I was of help!

This time, I checked the request running on aws-sdk (Node.js) as shown in the screenshot below.

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/31458364/217077896-233a494e-65b7-4f78-afb6-7d5a05239fb4.png">

I think you can check requests in a similar way for APIs other than AssumeRole.

Also, if you have any questions, feel free to contact us!
